language: node_js
node_js:
- '0.12'
deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: prueba-marco
  revision_type: github
  deployment_group: 4yopping
  application: TravisCI
  on:
    repo: 4yopping/travis-ec2
